program: /home/ads4015/ssl_project/sweep/wu_clip_pretrain_sweep.py
method: bayes
metric: {name: val_loss, goal: minimize}

parameters:
  global_batch_size: {values: [4, 8, 16, 32, 64]}
  mask_ratio: {min: 0.05, max: 0.5}
  mask_ratio_warmup: {values: [0.05, 0.1, 0.2, 0.3, 0.4, 0.5]}
  warmup_epochs: {values: [0, 5, 10, 20]}
  lr: {distribution: log_uniform, min: 0.00003, max: 0.001}
  ema_decay: {min: 0.93, max: 0.9995}
  temp_student: {min: 0.03, max: 0.2}
  temp_teacher: {min: 0.03, max: 0.2}
  embed_dim: {values: [192, 256, 384]}
  clip_temperature: {min: 0.03, max: 0.2}
  feature_size: {values: [24, 36, 48]}
  mask_patch_size: {values: [8, 16]}

  distill_logit: {min: -2.0, max: 2.0}
  reconstruction_logit: {min: -2.0, max: 2.0}
  align_logit: {min: -2.0, max: 2.0}
  clip_logit: {min: -2.0, max: 2.0}

command:
  - ${env}
  - python
  - ${program}
  - --config
  - /home/ads4015/ssl_project/sweep/wu_clip_pretrain_h100_config.yaml







