# config file for lsm pretraining

data:
  train_dir: "/midtier/paetzollab/scratch/ads4015/data_selma3d/lsm_fm_temp/train"
  val_dir: "/midtier/paetzollab/scratch/ads4015/data_selma3d/lsm_fm_temp/val"
  train_samp_size: 200
  val_samp_size: 50
  batch_size: 8

model:
  image_size: 96
  mask_ratio: 0.3
  lr: 0.0001
  ema_decay: 0.996
  mask_patch_size: 16 # base patch size for masking
  temp_student: 0.1 # temperature for student logits
  temp_teacher: 0.04 # temperature for teacher softmax

training:
  seed: 100
  max_epochs: 100
  patience: 10
  log_every_n_steps: 5
  project_name: 'ibot-pretrain-lsm'
















