input_root: /midtier/paetzollab/scratch/ads4015/data_selma3d/SELMA3D
output_root: /midtier/paetzollab/scratch/ads4015/data_selma3d/selma3d_finetune_patches
patch_size: [96, 96, 96]
patches_per_class: 25














